NES/Models/Position.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.User = new HashSet<User>();
            this.Department_Position = new HashSet<Department_Position>();
        }
    
        public int PositionID { get; set; }
        public string PositionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_Position> Department_Position { get; set; }
    }
}

NES/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using NES.Models;

namespace NES.Controllers
{
    public class PositionsController : Controller
    {
        private UserEntities db = new UserEntities();

        // GET: Positions
        public ActionResult Index()
        {
            //return View(db.Position.ToList());
            return View();
        }

        // Datatable Get Positions Data
        [HttpGet]
        public ActionResult GetPositionsData()
        {
            try
            {
                using (UserEntities db = new UserEntities())
                {
                    List<UserViewModel> positionsList = db.Position.Select(x => new UserViewModel
                    {
                        PositionID = x.PositionID,
                        PositionName = x.PositionName
                    }).ToList();

                    return Json(new { data = positionsList }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Positions/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Position.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PositionID,PositionName")] Position position)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Position.Add(position);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again or Contact to the Administrator.");
            }

            return View(position);
        }

        // GET: Positions/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = db.Position.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PositionID,PositionName")] Position position)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(position).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again or Contact to the Administrator.");
            }

            return View(position);
        }

        // GET: Positions/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Position.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Position.Find(id);
            db.Position.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NES/Views/Positions/Create.cshtml
<!-- Create New Position -->

@model NES.Models.Position

@{
    ViewBag.Title = "New Position";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom" style="width: 450px;">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header">Add New Position</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal mx-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-label-group">
                @*@Html.LabelFor(model => model.PositionName, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @Html.EditorFor(model => model.PositionName, new { htmlAttributes = new { @class = "form-control", @id = "positionInput", @type = "text", @placeholder = "Position name", @autofocus = "autofocus" } })
                <label for="positionInput" class="text-black-50">Role name</label>

                @Html.ValidationMessageFor(model => model.PositionName, "", new { @class = "text-danger" })
            </div>
    
            @*<input type="submit" value="Create" class="btn btn-default" />*@
            <button class="btn btn-primary btnSubmit btn-block tooltips" title="Save new Position data"><i class="mdi mdi-content-save-outline mdi-18px"></i> Add</button>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to List", "Index")*@
        @*@Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })*@
        <button class="btn btn-link tooltips" onclick="location.href='@Url.Action("Index", "Positions")'" title="Back to list"><i class="mdi mdi-arrow-left-circle-outline text-warning mdi-24px"></i></button>
    </div>
</body>
</html>

NES/Views/Positions/Edit.cshtml
<!-- Edit Positions -->

@model NES.Models.Position

@{
    ViewBag.Title = "Edit Position";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header" style="width: 450px;">Edit Position</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal mx-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PositionID)

            <div class="form-label-group">
                @*@Html.LabelFor(model => model.PositionName, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @Html.EditorFor(model => model.PositionName, new { htmlAttributes = new { @class = "form-control", @id = "positionInput", @type = "text", @placeholder = "Position name", @autofocus = "autofocus" } })
                <label for="positionInput" class="text-black-50">Position name</label>

                @Html.ValidationMessageFor(model => model.PositionName, "", new { @class = "text-danger" })
            </div>

            @*<input type="submit" value="Save" class="btn btn-default" />*@
            <button class="btn btn-primary btnSubmit btn-block tooltips" title="Save Organizational Unit data"><i class="mdi mdi-content-save-edit-outline mdi-18px"></i> Update</button>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to List", "Index")*@
        @*@Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })*@
        @*<button class="btn btn-warning btn-circle btn-circle-sm tooltips ml-3" onclick="location.href='@Url.Action("Index", "Positions")'" title="Back to list"><i class="mdi mdi-keyboard-backspace"></i></button>*@
        <button class="btn btn-link tooltips ml-3 p-0" onclick="location.href='@Url.Action("Index", "Positions")'" title="Back to list"><i class="mdi mdi-subdirectory-arrow-left text-warning mdi-18px"></i></button>
    </div>
</body>
</html>

NES/Views/Positions/Index.cshtml
<!-- Positions Administration -->

@{
    ViewBag.Title = "Positions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <div class="mr-3">
            <button class="btn btn-link d-md-none tooltips icn-color mr-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
            <button class="btn btn-link tooltips pr-1 pl-0 py-0" accesskey="n" title="Add new Position - Alt + Shift + N" onclick="location.href='@Url.Action("Create", "Positions")'"><i class="mdi mdi-pencil-plus-outline mdi-36px"></i></button>
        </div>
        <div>
            <h3 class="text-header">Positions Administration</h3>
        </div>
        <div class="ml-auto">
            <button class="btn btn-link icn-color align-bottom ml-3 p-0" id="helpTooltip"><i class="mdi mdi-help"></i></button>
        </div>
    </div>

    <!-- Page Body -->
    <!-- Datatables Table Definition -->
    <table class="table table-sm table-hover nowrap w-100" id="positionTable">
        <thead>
            <tr class="text-nowrap">
                <th>Position&nbsp;</th>
                <th class="disableReorder"></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    @section scripts {
        <script type="text/javascript">
        // Datatables
        var dataTable;
        $(document).ready(function () {
            dataTable = $("#positionTable").DataTable({
                ajax: {
                    url: "@Url.Action("GetPositionsData", "Positions")",
                    type: "GET",
                    datatype: "json",
                    error: function () {
                        NProgress.done();
                        alertify.alert('Data Retrieve Error!', '<b>Can\'t retrieve Positions data! Refresh page later or inform your admin.</b>');
                        $('.dataTables_empty').html('<span class="text-white bg-warning px-3 py-1">Data Error!</span>'); /* Display error on table too */
                    }
                },
                dom: /* dom with flex + HTML toolbar at header + Sort toolbar at header */
                    "<'d-flex pt-2'lB<'sortToolbar ml-auto'>f>" +
                    "<'d-flex'tr>" +
                    "<'d-flex mb-3'<'mr-3'i><'ml-auto'p>>",
                columns: [
                    { data: "PositionName",
                        className: 'text-nowrap'
                    },
                    { data: "PositionID",
                        render: function (data, type, row) {
                            var url = '@Url.Action("Edit", "Positions")/' + row.PositionID;
                            return "<a href='" + url + "' class='btn btn-link btn-sm tooltips text-primary px-0' title='Edit Position'><i class='mdi mdi-pencil-outline mdi-18px'></i></a> ";
                        },
                        sortable: false,
                        searchable: false,
                        orderable: false
                    }
                ],
                buttons: [
                    // Export buttons in dropdown
                    { extend: 'collection', className: 'btn btn-link tooltips shadow-none icn-color px-1 pt-0 pb-1', autoClose: true, text: '<span class="mdi mdi-table-arrow-right mdi-24px"></span>', titleAttr: 'Export to',
                        buttons: [
                            { extend: 'print', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-printer mdi-18px icn-color mr-2"> Print</span>' },
                            { extend: 'copy', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-clipboard-outline mdi-18px icn-color mr-2"> Clipboard</span>' },
                            { extend: 'csv', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-document-outline mdi-18px icn-color mr-2"> CSV text</span>' },
                            { extend: 'excel', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-excel-box-outline mdi-18px icn-color mr-2"> Excel</span>' },
                            { extend: 'pdf', className: 'btn btn-link text-capitalize text-decoration-none shadow-none p-2', text: '<span class="mdi mdi-file-pdf-box-outline mdi-18px icn-color mr-2"> PDF</span>' }
                        ]
                    }
                ],
                autoWidth: true,
                autoFill: true,
                processing: true,
                deferRender: true,
                async: true,
                fixedHeader: true,
                colReorder: true,
                select: {
                    info: false,
                    style: 'single',
                    selector: 'td:last-child'
                },
                stateSave: true,
                pagingType: "full_numbers",
                lengthMenu: [[10, 15, 25, 50, -1], ["10 rows\xa0", "15 rows\xa0", "25 rows\xa0", "50 rows\xa0", "All\xa0"]],
                language: {
                    emptyTable: "No data found! Please click on <b>Add New</b> Button.",
                    info: "Prikazano _START_ - _END_ od _TOTAL_",
                    infoEmpty: "0 - 0 od 0",
                    infoFiltered: "(_MAX_ ukupno)",
                    infoPostFix: "",
                    infoThousands: ",",
                    //lengthMenu: "Prikaži: _MENU_",
                    lengthMenu: "_MENU_",
                    loadingRecords: "Učitavanje...",
                    processing: function () {
                        NProgress.start();
                    },
                    searchPlaceholder: "Search all",
                    //search: '<i class="mdi mdi-magnify text-black-50"></i>',
                    search: "",
                    zeroRecords: "Traženi podaci nisu pronađeni!",
                    select: {
                        rows: {
                            _: "%d izabrano",
                            0: "Nema izabranih",
                            1: "1 izabran"
                        }
                    },
                    paginate: {
                        first: "<i class='mdi mdi-page-first'></i>",
                        last: "<i class='mdi mdi-page-last'></i>",
                        previous: "<i class='mdi mdi-chevron-left'></i>",
                        next: "<i class='mdi mdi-chevron-right'></i>"
                    }
                },
                initComplete: function () {
                    // Load progress done
                    NProgress.done();

                    // Add class to search field (fosus)
                    $('div.dataTables_filter input').addClass('search-focus');

                    // Focus to Search button
                    $('.search-focus').focus();

                    // Put search buttons in header - Clear global search
                    $("div.sortToolbar").html(
                        '<button class="btn btn-link tooltips icn-color shadow-none mt-2 p-0" accesskey="g" title="Clear global search - Alt + Shift + G" onclick="ResetSearch()"><i class="mdi mdi-magnify-minus-outline mdi-24px"></i></button>'
                    );

                    // Disable colReorder for Position Edit button
                    $('.disableReorder').css({ pointerEvents: "none" });

                    // Tooltipsters for dataTable
                    $('.tooltips').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: 'tooltipster-borderless'
                    });
                    $('.tooltips-warning').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: ['tooltipster-borderless', 'tooltipster-borderless-warning']
                    });
                    $('[data-toggle="tooltip"]').tooltip();
                }
            });
         });
        // End Datatable

        // Disable Position menu
        $('#positionsLink').toggleClass("d-none");
        
        // Table searsh reset
        function ResetSearch() {
            dataTable.search(' ');
            dataTable.draw();
            $('.search-focus').focus();
        };

        // Alertify settings
        alertify.defaults.transition = "slide";
        alertify.defaults.theme.ok = "btn btn-danger";
        alertify.defaults.theme.cancel = "btn btn-primary";
        alertify.defaults.theme.input = "form-control";
        alertify.alert().set({ modal: true, movable: false, pinnable: false });

        // Bottom header - appears in left bottom page corner
        $(document).ready(function () {
            $(document).on('scroll', function () {
                var scrollDistance = $(this).scrollTop();
                if (scrollDistance > 100) {
                    $('.header-bottom').fadeIn();
                } else {
                    $('.header-bottom').fadeOut();
                }
            });

            // Smooth scrolling using jQuery easing
            $(document).on('click', 'a.header-bottom', function (e) {
                var $anchor = $(this);
                $('html, body').stop().animate({
                    scrollTop: ($($anchor.attr('href')).offset().top)
                }, 1000, 'easeInOutExpo');
                e.preventDefault();
            });
        });
        </script>
    }
</body>
</html>