NES/Models/DepartmentPositionView.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentPositionView
    {
        public int DepPosID { get; set; }
        public string DepartmentName { get; set; }
        public string PositionName { get; set; }
    }
}

NES/Models/Department_Position.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_Position
    {
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public int DepPosID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
    }
}

NES/Controllers/DepartmentPositionController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using NES.Models;

namespace NES.Controllers
{
    public class DepartmentPositionController : Controller
    {
        private UserEntities db = new UserEntities();

        // GET: DepartmentPosition
        [HttpGet]
        public ActionResult Index()
        {
            //var department_Position = db.Department_Position.Include(d => d.Department).Include(d => d.Position).ToList();
            //return View(department_Position);
            return View();
        }

        [HttpGet]
        public ActionResult GetDepPosData()
        {
            try
            {
                var departmentPositionList = db.DepartmentPositionView.ToList();
                return Json(new { data = departmentPositionList }, JsonRequestBehavior.AllowGet);
                //return Json(new { data = db.DepartmentPositionView.ToList() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: DepartmentPosition/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department_Position department_Position = db.Department_Position.Find(id);
            if (department_Position == null)
            {
                return HttpNotFound();
            }
            return View(department_Position);
        }

        // GET: DepartmentPosition/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Department, "DepartmentID", "DepartmentName");
            ViewBag.PositionID = new SelectList(db.Position, "PositionID", "PositionName");
            return View();
        }

        // POST: DepartmentPosition/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentID,PositionID,DepPosID")] Department_Position departmentPosition)
        {
            if (departmentPosition is null)
            {
                throw new ArgumentNullException(nameof(departmentPosition));
            }

            try
            {
                if (ModelState.IsValid)
                {
                    db.Department_Position.Add(departmentPosition);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /*dataex*/)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again or Contact to the Administrator.");
            }

            ViewBag.DepartmentID = new SelectList(db.Department, "DepartmentID", "DepartmentName", departmentPosition.DepartmentID);
            ViewBag.PositionID = new SelectList(db.Position, "PositionID", "PositionName", departmentPosition.PositionID);
            return View(departmentPosition);
        }

        // GET: DepartmentPosition/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department_Position department_Position = db.Department_Position.Find(id);
            if (department_Position == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentID = new SelectList(db.Department, "DepartmentID", "DepartmentName", department_Position.DepartmentID);
            ViewBag.PositionID = new SelectList(db.Position, "PositionID", "PositionName", department_Position.PositionID);
            return View(department_Position);
        }

        // POST: DepartmentPosition/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentID,PositionID,DepPosID")] Department_Position departmentPosition)
        {
            if (departmentPosition is null)
            {
                throw new ArgumentNullException(nameof(departmentPosition));
            }

            if (ModelState.IsValid)
            {
                db.Entry(departmentPosition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.Department, "DepartmentID", "DepartmentName", departmentPosition.DepartmentID);
            ViewBag.PositionID = new SelectList(db.Position, "PositionID", "PositionName", departmentPosition.PositionID);
            return View(departmentPosition);
        }

        // GET: DepartmentPosition/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department_Position department_Position = db.Department_Position.Find(id);
            if (department_Position == null)
            {
                return HttpNotFound();
            }
            return View(department_Position);
        }

        // POST: DepartmentPosition/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department_Position department_Position = db.Department_Position.Find(id);
            db.Department_Position.Remove(department_Position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NES/Views/DepartmentPosition/Create.cshtml
@model NES.Models.Department_Position

@{
    ViewBag.Title = "New Dep<>Pos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header" style="width: 450px;">Add New Department <i class="mdi mdi-set-center"></i> Position</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group text-black-50">
                <div class="col-md-12 mt-2">
                    Department Name

                    @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-black-50">
                <div class="col-md-12">
                    Position Name

                    @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <button class="btn btn-primary btnSubmit btn-block tooltips" title="Save New Department <-> Position data"><i class="mdi mdi-content-save-edit-outline mdi-18px"></i> Update</button>
                </div>
            </div>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to List", "Index")*@
        @Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })
    </div>
</body>
</html>

NES/Views/DepartmentPosition/Delete.cshtml
@model NES.Models.Department_Position

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department_Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.PositionName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NES/Views/DepartmentPosition/Edit.cshtml
@model NES.Models.Department_Position

@{
    ViewBag.Title = "Edit Dep<>Pos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header" style="width: 450px;">Edit Department <i class="mdi mdi-set-center"></i> Position</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group text-black-50">
                <div class="col-md-12 mt-2">
                    Department Name

                    @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control text-header", disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-black-50">
                <div class="col-md-12">
                    Position Name

                    @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control", @type = "text", @autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.DepPosID)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <button class="btn btn-primary btnSubmit btn-block tooltips" title="Save Department <-> Position data"><i class="mdi mdi-content-save-edit-outline mdi-18px"></i> Update</button>
                </div>
            </div>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to List", "Index")*@
        @Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })
    </div>
</body>
</html>

NES/Views/DepartmentPosition/Index.cshtml
@model IEnumerable<NES.Models.Department_Position>

@{
    ViewBag.Title = "Department<>Position";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <div class="mr-3">
            <button class="btn btn-link d-md-none tooltips icn-color mr-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
            <button class="btn btn-link tooltips pr-1 pl-0 py-0" accesskey="n" title="Add new Department &#9902; Position - Alt + Shift + N" onclick="location.href='@Url.Action("Create", "DepartmentPosition")'"><i class="mdi mdi-pencil-plus-outline mdi-36px"></i></button>
        </div>
        <div>
            <h3 class="text-header ml-auto">Departments <i class="mdi mdi-set-center"></i> Positions Administration</h3>
        </div>
        <div class="ml-auto">
            <button class="btn btn-link icn-color align-bottom ml-3 p-0" id="helpTooltip"><i class="mdi mdi-help"></i></button>
        </div>
    </div>

    <!-- Page Body -->
    <!-- Datatables Table Definition -->
    <table class="table table-sm table-hover nowrap w-100" id="depPosTable">
        <thead>
            <tr class="text-nowrap">
                <th>Department Name&nbsp;</th>
                <th>Position Name&nbsp;</th>
                <th class="disableReorder"></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    @section scripts {
        <script type="text/javascript">
        // Datatables
        var dataTable;
        $(document).ready(function () {
            dataTable = $("#depPosTable").DataTable({
                ajax: {
                    url: "@Url.Action("GetDepPosData", "DepartmentPosition")",
                    type: "GET",
                    datatype: "json",
                    error: function () {
                        NProgress.done();
                        alertify.alert('Data Retrieve Error!', '<b>Can\'t retrieve Department &#9902 Positions data! Refresh page later or inform your admin.</b>');
                        $('.dataTables_empty').html('<span class="text-white bg-warning px-3 py-1">Data Error!</span>'); /* Display error on table too */
                    }
                },
                dom: /* dom with flex + HTML toolbar at header + Sort toolbar at header */
                    "<'d-flex pt-2'lB<'sortToolbar ml-auto'>f>" +
                    "<'d-flex'tr>" +
                    "<'d-flex mb-3'<'mr-3'i><'ml-auto'p>>",
                columns: [
                    { data: "DepartmentName",
                        className: 'text-nowrap'
                    },
                    { data: "PositionName",
                        className: 'text-nowrap'
                    },
                    { data: "PositionID",
                        render: function (data, type, row) {
                            var url = '@Url.Action("Edit", "DepartmentPosition")/' + row.DepPosID;
                            return "<a href='" + url + "' class='btn btn-link btn-sm tooltips text-primary px-0' title='Edit Position'><i class='mdi mdi-pencil-outline mdi-18px'></i></a> ";
                        },
                        sortable: false,
                        searchable: false,
                        orderable: false
                    }
                ],
                buttons: [
                    // Export buttons in dropdown
                    { extend: 'collection', className: 'btn btn-link tooltips shadow-none icn-color px-1 pt-0 pb-1', autoClose: true, text: '<span class="mdi mdi-table-arrow-right mdi-24px"></span>', titleAttr: 'Export to',
                        buttons: [
                            { extend: 'print', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-printer mdi-18px icn-color mr-2"> Print</span>' },
                            { extend: 'copy', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-clipboard-outline mdi-18px icn-color mr-2"> Clipboard</span>' },
                            { extend: 'csv', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-document-outline mdi-18px icn-color mr-2"> CSV text</span>' },
                            { extend: 'excel', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-excel-box-outline mdi-18px icn-color mr-2"> Excel</span>' },
                            { extend: 'pdf', className: 'btn btn-link text-capitalize text-decoration-none shadow-none p-2', text: '<span class="mdi mdi-file-pdf-box-outline mdi-18px icn-color mr-2"> PDF</span>' }
                        ]
                    }
                ],
                autoWidth: true,
                autoFill: true,
                processing: true,
                deferRender: true,
                async: true,
                fixedHeader: true,
                colReorder: true,
                select: {
                    info: false,
                    style: 'single',
                    selector: 'td:last-child'
                },
                stateSave: true,
                pagingType: "full_numbers",
                lengthMenu: [[10, 15, 25, 50, -1], ["10 rows\xa0", "15 rows\xa0", "25 rows\xa0", "50 rows\xa0", "All\xa0"]],
                language: {
                    emptyTable: "No data found! Please click on <b>Add New</b> Button.",
                    info: "Prikazano _START_ - _END_ od _TOTAL_",
                    infoEmpty: "0 - 0 od 0",
                    infoFiltered: "(_MAX_ ukupno)",
                    infoPostFix: "",
                    infoThousands: ",",
                    //lengthMenu: "Prikaži: _MENU_",
                    lengthMenu: "_MENU_",
                    loadingRecords: "Učitavanje...",
                    processing: function () {
                        NProgress.start();
                    },
                    searchPlaceholder: "Search all",
                    //search: '<i class="mdi mdi-magnify text-black-50"></i>',
                    search: "",
                    zeroRecords: "Traženi podaci nisu pronađeni!",
                    select: {
                        rows: {
                            _: "%d izabrano",
                            0: "Nema izabranih",
                            1: "1 izabran"
                        }
                    },
                    paginate: {
                        first: "<i class='mdi mdi-page-first'></i>",
                        last: "<i class='mdi mdi-page-last'></i>",
                        previous: "<i class='mdi mdi-chevron-left'></i>",
                        next: "<i class='mdi mdi-chevron-right'></i>"
                    }
                },
                initComplete: function () {
                    // Load progress done
                    NProgress.done();

                    // Add class to search field (fosus)
                    $('div.dataTables_filter input').addClass('search-focus');

                    // Focus to Search button
                    $('.search-focus').focus();

                    // Put search buttons in header - Clear global search
                    $("div.sortToolbar").html(
                        '<button class="btn btn-link tooltips icn-color shadow-none mt-2 p-0" accesskey="g" title="Clear global search - Alt + Shift + G" onclick="ResetSearch()"><i class="mdi mdi-magnify-minus-outline mdi-24px"></i></button>'
                    );

                    // Disable colReorder for Position Edit button
                    $('.disableReorder').css({ pointerEvents: "none" });

                    // Tooltipsters for dataTable
                    $('.tooltips').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: 'tooltipster-borderless'
                    });
                    $('.tooltips-warning').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: ['tooltipster-borderless', 'tooltipster-borderless-warning']
                    });
                    $('[data-toggle="tooltip"]').tooltip();
                }
            });
         });
        // End Datatable

        // Disable Position menu
        $('#positionsLink').toggleClass("d-none");

        // Table searsh reset
        function ResetSearch() {
            dataTable.search(' ');
            dataTable.draw();
            $('.search-focus').focus();
        };

        // Alertify settings
        alertify.defaults.transition = "slide";
        alertify.defaults.theme.ok = "btn btn-danger";
        alertify.defaults.theme.cancel = "btn btn-primary";
        alertify.defaults.theme.input = "form-control";
        alertify.alert().set({ modal: true, movable: false, pinnable: false });

        // Bottom header - appears in left bottom page corner
        $(document).ready(function () {
            $(document).on('scroll', function () {
                var scrollDistance = $(this).scrollTop();
                if (scrollDistance > 100) {
                    $('.header-bottom').fadeIn();
                } else {
                    $('.header-bottom').fadeOut();
                }
            });

            // Smooth scrolling using jQuery easing
            $(document).on('click', 'a.header-bottom', function (e) {
                var $anchor = $(this);
                $('html, body').stop().animate({
                    scrollTop: ($($anchor.attr('href')).offset().top)
                }, 1000, 'easeInOutExpo');
                e.preventDefault();
            });
        });
        </script>
    }
</body>
</html>