NES/Models/Role.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.User = new HashSet<User>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}

NES/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using NES.Models;

namespace NES.Controllers
{
    public class RolesController : Controller
    {
        private UserEntities db = new UserEntities();

        // GET: Roles
        [HttpGet]
        public ActionResult Index()
        {
            //return View(db.Role.ToList());
            return View();
        }

        // Datatable Get Roles Data
        [HttpGet]
        public ActionResult GetRolesData()
        {
            try
            {
                using (UserEntities db = new UserEntities())
                {
                    List<UserViewModel> rolesList = db.Role.Select(x => new UserViewModel
                    {
                        RoleID = x.RoleID,
                        RoleName = x.RoleName
                    }).ToList();

                    return Json(new { data = rolesList }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Roles/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,RoleName")] Role role)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Role.Add(role);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again or Contact to the Administrator.");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleID,RoleName")] Role role)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(role).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again or Contact to the Administrator.");
            }

            return View(role);
        }

        // GET: Roles/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Role role = db.Role.Find(id);
            db.Role.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NES/Views/Roles/Create.cshtml
<!-- Create Role -->

@model NES.Models.Role

@{
    ViewBag.Title = "New Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom" style="width: 450px;">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header">Add New Role</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal mx-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-label-group">
                @*@Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control", @id = "roleInput", @type = "text", @placeholder = "Role name", @autofocus = "autofocus" } })
                <label for="roleInput" class="text-black-50">Role name</label>

                @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
            </div>

            @*<input type="submit" value="Create" class="btn btn-default" />*@
            <button class="btn btn-primary btnSubmit btn-block tooltips" id="btnAdd" title="Save new Role data"><i class="mdi mdi-content-save-outline mdi-18px"></i> Add</button>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to list", "Index")*@
        @Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })
        @*<button class="btn btn-link tooltips text-warning" title="Back to list" onclick="location.href='@Url.Action("Index", "Roles")'"><i class="mdi mdi-arrow-left-circle mdi-24px"></i></button>*@
    </div>
</body>
</html>

NES/Views/Roles/Delete.cshtml
@model NES.Models.Role

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Positions</title>
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header" @*style="width: 450px;"*@>Delete Role</h3>
    </div>

    <div class="mx-3">
        <h4 class="font-weight-normal mt-2">Are you sure you want to delete this?</h4>
        <dl class="dl-horizontal">
            <dt class="text-black-50">
                Role Name:
            </dt>
            <dd class="lead font-weight-normal mt-2">
                @Html.DisplayFor(model => model.RoleName)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <button class="btn btn-warning btnSubmit btn-block tooltips" title="Delete Role!" disabled><i class="mdi mdi-delete-alert-outline mdi-18px"></i> Delete</button>

                @*<input type="submit" value="Delete" class="btn btn-default" /> |*@
            </div>
        }
    </div>

    <div class="mt-2">
        @*@Html.ActionLink("Back to List", "Index")*@
        @Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })
    </div>
</body>
</html>

NES/Views/Roles/Edit.cshtml
<!-- Edit Role -->

@model NES.Models.Role

@{
    ViewBag.Title = "Edit Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <!-- Page Header -->
    <div class="d-flex border-bottom">
        <button class="btn btn-link d-md-none tooltips icn-color mr-3 mb-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
        <h3 class="text-header" style="width: 450px;">Edit Role</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal mx-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.RoleID)

            <div class="form-label-group">
                @*@Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control", @id = "roleInput", @type = "text", @placeholder = "Role name", @autofocus = "autofocus" } })
                <label for="roleInput" class="text-black-50">Role name</label>

                @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
            </div>

            @*<input type="submit" value="Save" class="btn btn-default" />*@
            <button class="btn btn-primary btnSubmit btn-block tooltips" id="btnAdd" title="Save Role data"><i class="mdi mdi-content-save-edit-outline mdi-18px"></i> Update</button>
        </div>
    }

    <div>
        @*@Html.ActionLink("Back to list", "Index")*@
        @Html.ActionLink("\u21A9", "Index", null, new { @class = "btn btn-link tooltips text-warning text-decoration-none", @title = "Back to list" })
        @*<button class="btn btn-link tooltips text-warning" title="Back to list" onclick="location.href='@Url.Action("Index", "Roles")'"><i class="mdi mdi-arrow-left-circle mdi-24px"></i></button>*@
    </div>
</body>
</html>

NES/Views/Roles/Index.cshtml
<!-- Roles Administration -->

@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <!-- Page Header -->
    @*<div class="d-flex border-bottom">
            <button class="btn btn-link d-md-none tooltips icn-color mr-1 pt-0 px-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
            <a href="~/Roles/Create" class="btn btn-link tooltips pt-0 px-0" title="Add new Role"><span class="mdi mdi-badge-account-horizontal-outline mdi-36px"></span></a>
            <span class="font-weight-bolder text-primary mt-2 mr-3 ml-1">+</span>

            <h3 class="text-header ml-auto">Roles Administration</h3>
        </div>*@

    <div class="d-flex border-bottom">
        <div class="mr-3">
            <button class="btn btn-link d-md-none tooltips icn-color mr-1 p-0" id="sidebarToggleTop" title="Show/Hide Sidebar"><i class="mdi mdi-menu mdi-36px"></i></button>
            <button class="btn btn-link tooltips pr-1 pl-0 py-0" accesskey="n" title="Add new Role - Alt + Shift + N" onclick="location.href='@Url.Action("Create", "Roles")'"><i class="mdi mdi-pencil-plus-outline mdi-36px"></i></button>
        </div>
        <div>
            <h3 class="text-header">Roles Administration</h3>
        </div>
        <div class="ml-auto">
            <button class="btn btn-link icn-color p-0 align-bottom" id="helpTooltip"><i class="mdi mdi-help"></i></button>
        </div>
    </div>

    <!-- Page Body -->
    <!-- Datatables Table Definition -->
    <table class="table table-sm table-hover nowrap w-100" id="roleTable">
        <thead>
            <tr class="text-nowrap">
                <th>Role&nbsp;</th>
                <th class="disableReorder"></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    @section scripts {
        <script type="text/javascript">
        // Datatables
        var dataTable;
        $(document).ready(function () {
            dataTable = $("#roleTable").DataTable({
                ajax: {
                    url: "@Url.Action("GetRolesData", "Roles")",
                    type: "GET",
                    datatype: "json",
                    error: function () {
                        NProgress.done();
                        alertify.alert('Data Retrieve Error!', '<b>Can\'t retrieve Roles data! Refresh page later or inform your admin.</b>');
                        $('.dataTables_empty').html('<span class="text-white bg-warning px-3 py-1">Data Error!</span>'); /* Display error on table too */
                    }
                },
                dom: /* dom with flex + HTML toolbar at header + Sort toolbar at header */
                    "<'d-flex pt-2'lB<'sortToolbar ml-auto'>f>" +
                    "<'d-flex'tr>" +
                    "<'d-flex mb-3'<'mr-3'i><'ml-auto'p>>",
                columns: [
                    { data: "RoleName",
                        className: 'text-nowrap'
                    },
                    { data: "RoleID",
                        render: function (data, type, row) {
                            var url = '@Url.Action("Edit", "Roles")/' + row.RoleID;
                            return "<a href='" + url + "' class='btn btn-link btn-sm tooltips text-primary px-0' title='Edit Role'><i class='mdi mdi-pencil-outline mdi-18px'></i></a> ";
                        },
                        sortable: false,
                        searchable: false,
                        orderable: false
                    }
                ],
                buttons: [
                    // Export buttons in dropdown
                    { extend: 'collection', className: 'btn btn-link tooltips shadow-none icn-color px-1 pt-0 pb-1', autoClose: true, text: '<span class="mdi mdi-table-arrow-right mdi-24px"></span>', titleAttr: 'Export to',
                        buttons: [
                            { extend: 'print', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-printer mdi-18px icn-color mr-2"> Print</span>' },
                            { extend: 'copy', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-clipboard-outline mdi-18px icn-color mr-2"> Clipboard</span>' },
                            { extend: 'csv', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-document-outline mdi-18px icn-color mr-2"> CSV text</span>' },
                            { extend: 'excel', className: 'btn btn-link text-capitalize text-decoration-none shadow-none border-bottom p-2', text: '<span class="mdi mdi-file-excel-box-outline mdi-18px icn-color mr-2"> Excel</span>' },
                            { extend: 'pdf', className: 'btn btn-link text-capitalize text-decoration-none shadow-none p-2', text: '<span class="mdi mdi-file-pdf-box-outline mdi-18px icn-color mr-2"> PDF</span>' }
                        ]
                    }
                ],
                autoWidth: true,
                autoFill: true,
                processing: true,
                deferRender: true,
                async: true,
                fixedHeader: true,
                colReorder: true,
                select: {
                    info: false,
                    style: 'single',
                    selector: 'td:last-child'
                },
                stateSave: true,
                pagingType: "full_numbers",
                lengthMenu: [[10, 15, 25, 50, -1], ["10 rows\xa0", "15 rows\xa0", "25 rows\xa0", "50 rows\xa0", "All\xa0"]],
                language: {
                    emptyTable: "No data found! Please click on <b>Add New</b> Button.",
                    info: "Prikazano _START_ - _END_ od _TOTAL_",
                    infoEmpty: "0 - 0 od 0",
                    infoFiltered: "(_MAX_ ukupno)",
                    infoPostFix: "",
                    infoThousands: ",",
                    //lengthMenu: "Prikaži: _MENU_",
                    lengthMenu: "_MENU_",
                    loadingRecords: "Učitavanje...",
                    processing: function () {
                        NProgress.start();
                    },
                    searchPlaceholder: "Search all",
                    //search: '<i class="mdi mdi-magnify text-black-50"></i>',
                    search: "",
                    zeroRecords: "Traženi podaci nisu pronađeni!",
                    select: {
                        rows: {
                            _: "%d izabrano",
                            0: "Nema izabranih",
                            1: "1 izabran"
                        }
                    },
                    paginate: {
                        first: "<i class='mdi mdi-page-first'></i>",
                        last: "<i class='mdi mdi-page-last'></i>",
                        previous: "<i class='mdi mdi-chevron-left'></i>",
                        next: "<i class='mdi mdi-chevron-right'></i>"
                    }
                },
                initComplete: function () {
                    // Load progress done
                    NProgress.done();

                    // Add class to search field (fosus)
                    $('div.dataTables_filter input').addClass('search-focus');

                    // Focus to Search button
                    $('.search-focus').focus();

                    // Put search buttons in header - Clear global search
                    $("div.sortToolbar").html(
                        '<button class="btn btn-link tooltips icn-color shadow-none mt-2 p-0" accesskey="g" title="Clear global search - Alt + Shift + G" onclick="ResetSearch()"><i class="mdi mdi-magnify-minus-outline mdi-24px"></i></button>'
                    );

                    // Disable colReorder for Position Edit button
                    $('.disableReorder').css({ pointerEvents: "none" });

                    // Tooltipsters for dataTable
                    $('.tooltips').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: 'tooltipster-borderless'
                    });
                    $('.tooltips-warning').tooltipster({
                        delay: 500,
                        distance: 2,
                        theme: ['tooltipster-borderless', 'tooltipster-borderless-warning']
                    });
                    $('[data-toggle="tooltip"]').tooltip();
                }
            });
         });
        // End Datatable

        // Disable Position menu
        $('#rolesLink').toggleClass("d-none");

        // Table searsh reset
        function ResetSearch() {
            dataTable.search(' ');
            dataTable.draw();
            $('.search-focus').focus();
        };

        // Alertify settings
        alertify.defaults.transition = "slide";
        alertify.defaults.theme.ok = "btn btn-danger";
        alertify.defaults.theme.cancel = "btn btn-primary";
        alertify.defaults.theme.input = "form-control";
        alertify.alert().set({ modal: true, movable: false, pinnable: false });

        // Bottom header - appears in left bottom page corner
        $(document).ready(function () {
            $(document).on('scroll', function () {
                var scrollDistance = $(this).scrollTop();
                if (scrollDistance > 100) {
                    $('.header-bottom').fadeIn();
                } else {
                    $('.header-bottom').fadeOut();
                }
            });

            // Smooth scrolling using jQuery easing
            $(document).on('click', 'a.header-bottom', function (e) {
                var $anchor = $(this);
                $('html, body').stop().animate({
                    scrollTop: ($($anchor.attr('href')).offset().top)
                }, 1000, 'easeInOutExpo');
                e.preventDefault();
            });
        });
        </script>
    }
</body>
</html>